(
    WAITING_SM_DP_LINK,
    WAITING_ACTIVATION_CODE_LINK,
    WAITING_SM_DP_QR,
    WAITING_ACTIVATION_CODE_QR,
    WAITING_QR_DATA,
    WAITING_QR_IMAGE,
    WAITING_LPA_STRING,
    WAITING_ADD_ESIM_SM_DP,
    WAITING_ADD_ESIM_CODE,
    WAITING_ADD_ESIM_DESC,
    WAITING_ESIM_SELECTION,
    WAITING_ADD_ESIM_LPA,
    WAITING_ADD_ESIM_LPA_DESC,
    WAITING_ADD_ESIM_URL,
    WAITING_ADD_ESIM_URL_DESC,
    WAITING_ICCID,
) = range(16)

PUBLIC_CALLBACKS = {"check_iccid", "create_link_qr", "back_to_menu"}
